/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AccessTokens: () => import('#controllers/access_tokens_controller'),
  admin: {
    Gateways: () => import('#controllers/admin/gateways_controller'),
  },
  auth: {
    ClientTokens: () => import('#controllers/auth/client_tokens_controller'),
  },
  gateways: {
    GatewayProvision: () => import('#controllers/gateways/gateway_provision_controller'),
    GatewayRegistration: () => import('#controllers/gateways/gateway_registration_controller'),
  },
  NewAccount: () => import('#controllers/new_account_controller'),
  Profile: () => import('#controllers/profile_controller'),
  sms: {
    Sms: () => import('#controllers/sms/sms_controller'),
  },
}
