/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'
import type { ClientAbility } from '#enums/ability'
import type { AuditAction, ActorType } from '#enums/audit_action'
import type { GatewayStatus, SimState } from '#enums/gateway_status'
import type { UssdKind, UssdStatus } from '#enums/ussd'
import type { ErrorCode } from '#enums/error_code'
import type { SmsAttemptStatus, SmsStatus } from '#enums/sms_status'
import type { SmsEvent } from '#enums/sms_event'
import type { TenantSettings, TenantStatus, UserRole } from '#enums/tenant'

export class ApiClientAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = ApiClientAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ApiClientSchema extends BaseModel {
  static $columns = ['abilities', 'clientId', 'clientSecretHash', 'createdAt', 'id', 'isActive', 'lastUsedAt', 'name', 'rateLimitPerMin', 'tenantId', 'uid', 'updatedAt'] as const
  $columns = ApiClientSchema.$columns
  @column()
  declare abilities: ClientAbility[]
  @column()
  declare clientId: string
  @column()
  declare clientSecretHash: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string
  @column()
  declare rateLimitPerMin: number
  @column()
  declare tenantId: number
  @column()
  declare uid: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class AuditLogSchema extends BaseModel {
  static $columns = ['action', 'actorId', 'actorLabel', 'actorType', 'createdAt', 'id', 'ipAddress', 'metadata', 'resourceId', 'resourceType', 'tenantId', 'userAgent'] as const
  $columns = AuditLogSchema.$columns
  @column()
  declare action: AuditAction
  @column()
  declare actorId: number | null
  @column()
  declare actorLabel: string | null
  @column()
  declare actorType: ActorType
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare ipAddress: string | null
  @column()
  declare metadata: Record<string, unknown> | null
  @column()
  declare resourceId: string | null
  @column()
  declare resourceType: string | null
  @column()
  declare tenantId: number | null
  @column()
  declare userAgent: string | null
}

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class GatewayAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = GatewayAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class GatewayEventSchema extends BaseModel {
  static $columns = ['createdAt', 'event', 'gatewayId', 'id', 'payload', 'severity'] as const
  $columns = GatewayEventSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare event: string
  @column()
  declare gatewayId: number
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare payload: Record<string, unknown> | null
  @column()
  declare severity: string
}

export class GatewaySessionSchema extends BaseModel {
  static $columns = ['appVersion', 'connectedAt', 'disconnectReason', 'disconnectedAt', 'gatewayId', 'id', 'ipAddress', 'nodeId'] as const
  $columns = GatewaySessionSchema.$columns
  @column()
  declare appVersion: string | null
  @column.dateTime()
  declare connectedAt: DateTime
  @column()
  declare disconnectReason: string | null
  @column.dateTime()
  declare disconnectedAt: DateTime | null
  @column()
  declare gatewayId: number
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare ipAddress: string | null
  @column()
  declare nodeId: string
}

export class GatewaySchema extends BaseModel {
  static $columns = ['androidVersion', 'appVersion', 'approvedAt', 'approvedBy', 'battery', 'claimCode', 'claimCodeExpiresAt', 'createdAt', 'deviceId', 'id', 'isActive', 'isCharging', 'lastConnectedAt', 'lastSeenAt', 'manufacturer', 'maxInFlight', 'model', 'name', 'network', 'nodeId', 'priority', 'signalLevel', 'status', 'tenantId', 'uid', 'updatedAt'] as const
  $columns = GatewaySchema.$columns
  @column()
  declare androidVersion: string | null
  @column()
  declare appVersion: string | null
  @column.dateTime()
  declare approvedAt: DateTime | null
  @column()
  declare approvedBy: number | null
  @column()
  declare battery: number | null
  @column()
  declare claimCode: string | null
  @column.dateTime()
  declare claimCodeExpiresAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare deviceId: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean
  @column()
  declare isCharging: boolean | null
  @column.dateTime()
  declare lastConnectedAt: DateTime | null
  @column.dateTime()
  declare lastSeenAt: DateTime | null
  @column()
  declare manufacturer: string | null
  @column()
  declare maxInFlight: number
  @column()
  declare model: string | null
  @column()
  declare name: string | null
  @column()
  declare network: string | null
  @column()
  declare nodeId: string | null
  @column()
  declare priority: number
  @column()
  declare signalLevel: number | null
  @column()
  declare status: GatewayStatus
  @column()
  declare tenantId: number | null
  @column()
  declare uid: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class JobSchema extends BaseModel {
  static $columns = ['attempts', 'createdAt', 'dedupeKey', 'id', 'lastError', 'leaseExpiresAt', 'lockedBy', 'maxAttempts', 'payload', 'queue', 'runAt', 'status', 'updatedAt'] as const
  $columns = JobSchema.$columns
  @column()
  declare attempts: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare dedupeKey: string | null
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare lastError: string | null
  @column.dateTime()
  declare leaseExpiresAt: DateTime | null
  @column()
  declare lockedBy: string | null
  @column()
  declare maxAttempts: number
  @column()
  declare payload: any
  @column()
  declare queue: string
  @column.dateTime()
  declare runAt: DateTime
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class OperatorUssdCommandSchema extends BaseModel {
  static $columns = ['command', 'createdAt', 'id', 'isActive', 'kind', 'operatorId', 'parserKey', 'steps', 'updatedAt'] as const
  $columns = OperatorUssdCommandSchema.$columns
  @column()
  declare command: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean
  @column()
  declare kind: UssdKind
  @column()
  declare operatorId: number
  @column()
  declare parserKey: string
  @column()
  declare steps: string[]
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class OperatorSchema extends BaseModel {
  static $columns = ['code', 'country', 'createdAt', 'id', 'isActive', 'mcc', 'mnc', 'name', 'phonePrefixes', 'updatedAt'] as const
  $columns = OperatorSchema.$columns
  @column()
  declare code: string
  @column()
  declare country: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean
  @column()
  declare mcc: string | null
  @column()
  declare mnc: string | null
  @column()
  declare name: string
  @column()
  declare phonePrefixes: string[]
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class SimProfileSchema extends BaseModel {
  static $columns = ['balanceCheckIntervalMin', 'balanceCheckedAt', 'counterDate', 'createdAt', 'dailyQuota', 'gatewayId', 'iccidHash', 'id', 'imsiHash', 'isActive', 'label', 'nextAvailableAt', 'operatorId', 'phoneNumber', 'sentToday', 'slot', 'smsBalance', 'smsPerMinute', 'state', 'uid', 'updatedAt'] as const
  $columns = SimProfileSchema.$columns
  @column()
  declare balanceCheckIntervalMin: number
  @column.dateTime()
  declare balanceCheckedAt: DateTime | null
  @column.date()
  declare counterDate: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare dailyQuota: number | null
  @column()
  declare gatewayId: number
  @column()
  declare iccidHash: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare imsiHash: string | null
  @column()
  declare isActive: boolean
  @column()
  declare label: string | null
  @column.dateTime()
  declare nextAvailableAt: DateTime | null
  @column()
  declare operatorId: number | null
  @column()
  declare phoneNumber: string | null
  @column()
  declare sentToday: number
  @column()
  declare slot: number
  @column()
  declare smsBalance: number | null
  @column()
  declare smsPerMinute: number
  @column()
  declare state: SimState
  @column()
  declare uid: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class SmsAttemptSchema extends BaseModel {
  static $columns = ['attemptNo', 'durationMs', 'errorCode', 'errorMessage', 'finishedAt', 'gatewayId', 'id', 'simProfileId', 'smsMessageId', 'startedAt', 'status'] as const
  $columns = SmsAttemptSchema.$columns
  @column()
  declare attemptNo: number
  @column()
  declare durationMs: number | null
  @column()
  declare errorCode: ErrorCode | null
  @column()
  declare errorMessage: string | null
  @column.dateTime()
  declare finishedAt: DateTime | null
  @column()
  declare gatewayId: number | null
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare simProfileId: number | null
  @column()
  declare smsMessageId: bigint | number
  @column.dateTime()
  declare startedAt: DateTime
  @column()
  declare status: SmsAttemptStatus
}

export class SmsDailyStatSchema extends BaseModel {
  static $columns = ['avgSendMs', 'createdAt', 'date', 'delivered', 'failed', 'id', 'operatorId', 'pending', 'segments', 'sent', 'simProfileId', 'tenantId', 'total', 'updatedAt'] as const
  $columns = SmsDailyStatSchema.$columns
  @column()
  declare avgSendMs: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.date()
  declare date: DateTime
  @column()
  declare delivered: number
  @column()
  declare failed: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare operatorId: number | null
  @column()
  declare pending: number
  @column()
  declare segments: number
  @column()
  declare sent: number
  @column()
  declare simProfileId: number | null
  @column()
  declare tenantId: number | null
  @column()
  declare total: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class SmsEventSchema extends BaseModel {
  static $columns = ['createdAt', 'event', 'gatewayId', 'id', 'payload', 'smsMessageId'] as const
  $columns = SmsEventSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare event: SmsEvent
  @column()
  declare gatewayId: number | null
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare payload: Record<string, unknown> | null
  @column()
  declare smsMessageId: bigint | number
}

export class SmsMessageSchema extends BaseModel {
  static $columns = ['apiClientId', 'assignedAt', 'attempts', 'bodyHash', 'createdAt', 'deliveredAt', 'dispatchBody', 'encoding', 'errorCode', 'errorMessage', 'expiresAt', 'failedAt', 'id', 'idempotencyKey', 'leaseExpiresAt', 'maxAttempts', 'messageBody', 'nextAttemptAt', 'priority', 'providerMessageId', 'queuedAt', 'recipient', 'recipientNormalized', 'reference', 'requestedGatewayId', 'requestedOperatorId', 'segments', 'sentAt', 'simProfileId', 'status', 'tenantId', 'uid', 'updatedAt'] as const
  $columns = SmsMessageSchema.$columns
  @column()
  declare apiClientId: number | null
  @column.dateTime()
  declare assignedAt: DateTime | null
  @column()
  declare attempts: number
  @column()
  declare bodyHash: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deliveredAt: DateTime | null
  @column()
  declare dispatchBody: string | null
  @column()
  declare encoding: string
  @column()
  declare errorCode: ErrorCode | null
  @column()
  declare errorMessage: string | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column.dateTime()
  declare failedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare idempotencyKey: string | null
  @column.dateTime()
  declare leaseExpiresAt: DateTime | null
  @column()
  declare maxAttempts: number
  @column()
  declare messageBody: string | null
  @column.dateTime()
  declare nextAttemptAt: DateTime | null
  @column()
  declare priority: number
  @column()
  declare providerMessageId: string | null
  @column.dateTime()
  declare queuedAt: DateTime | null
  @column()
  declare recipient: string
  @column()
  declare recipientNormalized: string
  @column()
  declare reference: string | null
  @column()
  declare requestedGatewayId: number | null
  @column()
  declare requestedOperatorId: number | null
  @column()
  declare segments: number
  @column.dateTime()
  declare sentAt: DateTime | null
  @column()
  declare simProfileId: number | null
  @column()
  declare status: SmsStatus
  @column()
  declare tenantId: number
  @column()
  declare uid: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class TenantSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'name', 'settings', 'slug', 'status', 'uid', 'updatedAt'] as const
  $columns = TenantSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare settings: TenantSettings
  @column()
  declare slug: string
  @column()
  declare status: TenantStatus
  @column()
  declare uid: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'isActive', 'password', 'role', 'tenantId', 'uid', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare role: UserRole
  @column()
  declare tenantId: number | null
  @column()
  declare uid: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UssdRequestSchema extends BaseModel {
  static $columns = ['command', 'completedAt', 'errorCode', 'errorMessage', 'id', 'kind', 'parsed', 'rawResponse', 'requestedAt', 'simProfileId', 'status', 'steps', 'uid'] as const
  $columns = UssdRequestSchema.$columns
  @column()
  declare command: string
  @column.dateTime()
  declare completedAt: DateTime | null
  @column()
  declare errorCode: ErrorCode | null
  @column()
  declare errorMessage: string | null
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare kind: UssdKind
  @column()
  declare parsed: Record<string, unknown> | null
  @column()
  declare rawResponse: string | null
  @column.dateTime()
  declare requestedAt: DateTime
  @column()
  declare simProfileId: number
  @column()
  declare status: UssdStatus
  @column()
  declare steps: string[]
  @column()
  declare uid: string
}

export class WebhookEndpointSchema extends BaseModel {
  static $columns = ['createdAt', 'disabledAt', 'events', 'failureCount', 'id', 'isActive', 'lastFailureAt', 'lastSuccessAt', 'secret', 'tenantId', 'uid', 'updatedAt', 'url'] as const
  $columns = WebhookEndpointSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare disabledAt: DateTime | null
  @column()
  declare events: string[]
  @column()
  declare failureCount: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean
  @column.dateTime()
  declare lastFailureAt: DateTime | null
  @column.dateTime()
  declare lastSuccessAt: DateTime | null
  @column()
  declare secret: string
  @column()
  declare tenantId: number
  @column()
  declare uid: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare url: string
}
