/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

/// <reference path="./manifest.d.ts" />
import type { InferData, InferVariants } from '@adonisjs/core/types/transformers'
import type GatewayTransformer from '#transformers/gateway_transformer'
import type SimProfileTransformer from '#transformers/sim_profile_transformer'
import type SmsMessageTransformer from '#transformers/sms_message_transformer'
import type UserTransformer from '#transformers/user_transformer'

export namespace Data {
  export type Gateway = InferData<GatewayTransformer>
  export namespace Gateway {
    export type Variants = InferVariants<GatewayTransformer>
  }
  export type SimProfile = InferData<SimProfileTransformer>
  export namespace SimProfile {
    export type Variants = InferVariants<SimProfileTransformer>
  }
  export type SmsMessage = InferData<SmsMessageTransformer>
  export namespace SmsMessage {
    export type Variants = InferVariants<SmsMessageTransformer>
  }
  export type User = InferData<UserTransformer>
  export namespace User {
    export type Variants = InferVariants<UserTransformer>
  }
}
