import { BaseSchema } from '@adonisjs/lucid/schema'

export default class extends BaseSchema {
  protected tableName = 'gateways'

  async up() {
    this.schema.createTable(this.tableName, (table) => {
      table.increments('id').notNullable()
      table.string('uid', 40).notNullable().unique()

      /**
       * A null tenant means the device belongs to the shared pool and may
       * carry traffic for any tenant. A set tenant dedicates the device.
       */
      table
        .integer('tenant_id')
        .unsigned()
        .nullable()
        .references('id')
        .inTable('tenants')
        .onDelete('SET NULL')

      /**
       * Stable identifier generated by the app on first launch and kept in
       * encrypted storage. Re-installing the app produces a new device.
       */
      table.string('device_id', 128).notNullable().unique()

      table.string('name').nullable()
      table.string('manufacturer', 64).nullable()
      table.string('model', 64).nullable()
      table.string('android_version', 32).nullable()
      table.string('app_version', 32).nullable()

      /**
       * pending_approval | offline | online | busy | disabled | error
       */
      table.string('status', 20).notNullable().defaultTo('pending_approval')
      table.timestamp('approved_at').nullable()
      table
        .integer('approved_by')
        .unsigned()
        .nullable()
        .references('id')
        .inTable('users')
        .onDelete('SET NULL')

      /**
       * One-time code the device exchanges for its access token after an
       * operator approves it.
       */
      table.string('claim_code', 64).nullable().unique()
      table.timestamp('claim_code_expires_at').nullable()

      /**
       * Lower value wins when the selector scores candidates.
       */
      table.integer('priority').notNullable().defaultTo(100)
      table.boolean('is_active').notNullable().defaultTo(true)

      table.integer('battery').nullable()
      table.boolean('is_charging').nullable()
      table.string('network', 16).nullable()
      table.integer('signal_level').nullable()
      table.timestamp('last_seen_at').nullable()
      table.timestamp('last_connected_at').nullable()

      table.timestamp('created_at').notNullable()
      table.timestamp('updated_at').nullable()

      table.index(['status', 'is_active'], 'gateways_status_index')
      table.index(['tenant_id'], 'gateways_tenant_id_index')
    })
  }

  async down() {
    this.schema.dropTable(this.tableName)
  }
}
